"""
Add unique constraints and indexes

- Add unique constraint to `song_id` in `song_lyrics` and `song_resources` tables to
enforce one-to-one relationships.
- Add indexes to `song_usage` table on `song_id`, (`song_id`, `used_date`), and
`used_date` columns to improve query performance.

Revision ID: 6855702b1f93
Revises: 7afcaed7ddac
Create Date: 2025-11-28 13:06:43.506138

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6855702b1f93'
down_revision: Union[str, Sequence[str], None] = '7afcaed7ddac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_song_lyrics_song_id', 'song_lyrics', ['song_id'])
    op.create_unique_constraint('uq_song_resources_song_id', 'song_resources', ['song_id'])
    op.create_index('idx_songusage_song_id', 'song_usage', ['song_id'], unique=False)
    op.create_index('idx_songusage_songid_date', 'song_usage', ['song_id', 'used_date'], unique=False)
    op.create_index('idx_songusage_used_date', 'song_usage', ['used_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_songusage_used_date', table_name='song_usage')
    op.drop_index('idx_songusage_songid_date', table_name='song_usage')
    op.drop_index('idx_songusage_song_id', table_name='song_usage')
    op.drop_constraint('uq_song_resources_song_id', 'song_resources', type_='unique')
    op.drop_constraint('uq_song_lyrics_song_id', 'song_lyrics', type_='unique')

    # ### end Alembic commands ###
