"""Add song_youtube_links table

Revision ID: fe5dc26c3f66
Revises: cd51e3c5b6e0
Create Date: 2026-02-21 11:10:59.477425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe5dc26c3f66"
down_revision: Union[str, Sequence[str], None] = "cd51e3c5b6e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - no adjustments were made ###
    op.create_table(
        "song_youtube_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_usage_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("start_seconds", sa.Integer(), nullable=True),
        sa.Column("end_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "end_seconds IS NULL OR end_seconds >= 0", name="check_end_non_negative"
        ),
        sa.CheckConstraint(
            (
                "start_seconds IS NULL OR end_seconds IS NULL OR "
                "start_seconds < end_seconds"
            ),
            name="check_start_before_end",
        ),
        sa.CheckConstraint(
            "start_seconds IS NULL OR start_seconds >= 0",
            name="check_start_non_negative",
        ),
        sa.ForeignKeyConstraint(
            ["song_usage_id"], ["song_usage.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_youtube_song_usage", "song_youtube_links", ["song_usage_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_youtube_song_usage", table_name="song_youtube_links")
    op.drop_table("song_youtube_links")
    # ### end Alembic commands ###
